import { AuditLogItem, ExceptionItem, FilingPeriod, GstF5Summary, Transaction } from "./api";

export const mockPeriod: FilingPeriod = {
  id: 202602,
  name: "Q2 2026",
  start_date: "2026-04-01",
  end_date: "2026-06-30",
  status: "REVIEW",
  created_at: "2026-05-24T09:00:00.000Z"
};

const examples: Transaction[] = [
  {
    id: 1,
    filing_period_id: mockPeriod.id,
    transaction_date: "2026-04-08",
    invoice_no: "S-1001",
    source_system: "Sample Dataset",
    transaction_type: "SALE",
    counterparty_name: "Marina Analytics Pte Ltd",
    counterparty_country: "SG",
    gl_account: "Sales",
    description: "Standard-rated sale",
    currency: "SGD",
    net_amount: 12000,
    gst_amount: 1080,
    gross_amount: 13080,
    original_tax_code: "SR",
    gst_treatment: "STANDARD_RATED_SUPPLY",
    classification_confidence: 0.96,
    classification_reason: "Singapore supply with GST charged at 9%.",
    review_status: "AUTO_CLASSIFIED",
    anomaly_score: 0.05,
    max_exception_severity: null
  },
  {
    id: 2,
    filing_period_id: mockPeriod.id,
    transaction_date: "2026-04-12",
    invoice_no: "EXP-9105",
    source_system: "Accounting API",
    transaction_type: "SALE",
    counterparty_name: "Seoul Electronics",
    counterparty_country: "KR",
    gl_account: "Export Sales",
    description: "Zero-rated sale missing export evidence",
    currency: "SGD",
    net_amount: 14400,
    gst_amount: 0,
    gross_amount: 14400,
    original_tax_code: "ZR",
    gst_treatment: "ZERO_RATED_SUPPLY",
    classification_confidence: 0.82,
    classification_reason: "Customer country indicates export sale, but export evidence is not linked.",
    review_status: "NEEDS_REVIEW",
    anomaly_score: 0.78,
    max_exception_severity: "HIGH"
  },
  {
    id: 3,
    filing_period_id: mockPeriod.id,
    transaction_date: "2026-04-19",
    invoice_no: "EX-2201",
    source_system: "Sample Dataset",
    transaction_type: "SALE",
    counterparty_name: "QCP Treasury Desk",
    counterparty_country: "SG",
    gl_account: "Exempt Revenue",
    description: "Exempt supply",
    currency: "SGD",
    net_amount: 30000,
    gst_amount: 0,
    gross_amount: 30000,
    original_tax_code: "ES",
    gst_treatment: "EXEMPT_SUPPLY",
    classification_confidence: 0.91,
    classification_reason: "Exempt financial service revenue flows to Box 3 without output tax.",
    review_status: "AUTO_CLASSIFIED",
    anomaly_score: 0.08,
    max_exception_severity: null
  },
  {
    id: 4,
    filing_period_id: mockPeriod.id,
    transaction_date: "2026-05-02",
    invoice_no: "OOS-7782",
    source_system: "Database Connector",
    transaction_type: "SALE",
    counterparty_name: "Offshore affiliate",
    counterparty_country: "US",
    gl_account: "Out-of-scope",
    description: "Out-of-scope transaction",
    currency: "USD",
    net_amount: 18500,
    gst_amount: 0,
    gross_amount: 18500,
    original_tax_code: "OS",
    gst_treatment: "OUT_OF_SCOPE_SUPPLY",
    classification_confidence: 0.88,
    classification_reason: "Out-of-scope supplies are excluded from GST F5 reporting.",
    review_status: "AUTO_CLASSIFIED",
    anomaly_score: 0.12,
    max_exception_severity: null
  },
  {
    id: 5,
    filing_period_id: mockPeriod.id,
    transaction_date: "2026-05-08",
    invoice_no: "P-4471",
    source_system: "CSV / Excel",
    transaction_type: "PURCHASE",
    counterparty_name: "CloudOps Pte Ltd",
    counterparty_country: "SG",
    gl_account: "Software",
    description: "Purchase with GST",
    currency: "SGD",
    net_amount: 9000,
    gst_amount: 810,
    gross_amount: 9810,
    original_tax_code: "TX",
    gst_treatment: "TAXABLE_PURCHASE",
    classification_confidence: 0.94,
    classification_reason: "Valid taxable purchase with GST amount tracked separately for Box 7.",
    review_status: "AUTO_CLASSIFIED",
    anomaly_score: 0.03,
    max_exception_severity: null
  },
  {
    id: 6,
    filing_period_id: mockPeriod.id,
    transaction_date: "2026-05-14",
    invoice_no: null,
    source_system: "CSV / Excel",
    transaction_type: "PURCHASE",
    counterparty_name: "Event Vendor Pte Ltd",
    counterparty_country: "SG",
    gl_account: "Marketing",
    description: "Input tax claim missing invoice",
    currency: "SGD",
    net_amount: 4200,
    gst_amount: 378,
    gross_amount: 4578,
    original_tax_code: "TX",
    gst_treatment: "REVIEW_REQUIRED",
    classification_confidence: 0.58,
    classification_reason: "Input tax claim requires valid tax invoice or import permit.",
    review_status: "NEEDS_REVIEW",
    anomaly_score: 0.86,
    max_exception_severity: "HIGH"
  },
  {
    id: 7,
    filing_period_id: mockPeriod.id,
    transaction_date: "2026-05-18",
    invoice_no: "DUP-3004",
    source_system: "Accounting API",
    transaction_type: "SALE",
    counterparty_name: "Marina Analytics Pte Ltd",
    counterparty_country: "SG",
    gl_account: "Sales",
    description: "Duplicate invoice",
    currency: "SGD",
    net_amount: 7600,
    gst_amount: 684,
    gross_amount: 8284,
    original_tax_code: "SR",
    gst_treatment: "STANDARD_RATED_SUPPLY",
    classification_confidence: 0.9,
    classification_reason: "Treatment appears standard-rated, but duplicate invoice number needs review.",
    review_status: "NEEDS_REVIEW",
    anomaly_score: 0.72,
    max_exception_severity: "MEDIUM"
  },
  {
    id: 8,
    filing_period_id: mockPeriod.id,
    transaction_date: "2026-06-02",
    invoice_no: "FX-9002",
    source_system: "Database Connector",
    transaction_type: "PURCHASE",
    counterparty_name: "US SaaS Vendor",
    counterparty_country: "US",
    gl_account: "Subscriptions",
    description: "Foreign currency transaction missing FX rate",
    currency: "USD",
    net_amount: 2000,
    gst_amount: 180,
    gross_amount: 2180,
    original_tax_code: "RC",
    gst_treatment: "REVIEW_REQUIRED",
    classification_confidence: 0.61,
    classification_reason: "Foreign currency conversion missing; SGD amount requires validation.",
    review_status: "NEEDS_REVIEW",
    anomaly_score: 0.67,
    max_exception_severity: "MEDIUM"
  },
  {
    id: 9,
    filing_period_id: mockPeriod.id,
    transaction_date: "2026-06-11",
    invoice_no: "LC-5010",
    source_system: "Sample Dataset",
    transaction_type: "PURCHASE",
    counterparty_name: "Employee reimbursement",
    counterparty_country: "SG",
    gl_account: "Staff Claims",
    description: "Low-confidence AI classification",
    currency: "SGD",
    net_amount: 630,
    gst_amount: 56.7,
    gross_amount: 686.7,
    original_tax_code: "TX",
    gst_treatment: "REVIEW_REQUIRED",
    classification_confidence: 0.52,
    classification_reason: "Employee reimbursement needs review for input tax claim eligibility.",
    review_status: "NEEDS_REVIEW",
    anomaly_score: 0.62,
    max_exception_severity: "MEDIUM"
  },
  {
    id: 10,
    filing_period_id: mockPeriod.id,
    transaction_date: "2026-06-17",
    invoice_no: "CAR-8020",
    source_system: "CSV / Excel",
    transaction_type: "PURCHASE",
    counterparty_name: "Prestige Motors Pte Ltd",
    counterparty_country: "SG",
    gl_account: "Transport",
    description: "Human override example for motor car expense",
    currency: "SGD",
    net_amount: 5800,
    gst_amount: 522,
    gross_amount: 6322,
    original_tax_code: "TX",
    gst_treatment: "DISALLOWED_INPUT_TAX",
    classification_confidence: 0.74,
    classification_reason: "Motor car expense marked non-claimable after human override.",
    review_status: "OVERRIDDEN",
    anomaly_score: 0.44,
    max_exception_severity: "LOW"
  }
];

export const mockTransactions: Transaction[] = Array.from({ length: 128 }, (_, index) => {
  const base = index < examples.length ? examples[index] : examples[0];
  return {
    ...base,
    id: index + 1,
    invoice_no: base.invoice_no ? `${base.invoice_no}-${Math.floor(index / examples.length) + 1}` : `AUTO-${index + 1}`,
    description: index < examples.length ? base.description : "Standard-rated sale",
    gst_treatment: index < examples.length ? base.gst_treatment : "STANDARD_RATED_SUPPLY",
    classification_confidence: index < examples.length ? base.classification_confidence : 0.93,
    classification_reason: index < examples.length ? base.classification_reason : "Singapore supply with GST charged at 9%.",
    review_status: index < examples.length ? base.review_status : "AUTO_CLASSIFIED",
    anomaly_score: index < examples.length ? base.anomaly_score : 0.04,
    max_exception_severity: index < examples.length ? base.max_exception_severity : null,
    net_amount: Number((base.net_amount + index * 125).toFixed(2)),
    gst_amount: Number((base.gst_amount + (base.gst_amount ? index * 11.25 : 0)).toFixed(2)),
    gross_amount: Number((base.gross_amount + index * 136.25).toFixed(2))
  };
});

export const mockExceptions: ExceptionItem[] = [
  {
    id: 1,
    transaction_id: 2,
    severity: "HIGH",
    exception_type: "MISSING_EXPORT_EVIDENCE",
    message: "Zero-rated sale is missing export evidence.",
    resolved: false,
    status: "Open",
    invoice_no: "EXP-9105",
    created_at: "2026-05-24T09:12:00.000Z"
  },
  {
    id: 2,
    transaction_id: 6,
    severity: "HIGH",
    exception_type: "MISSING_TAX_INVOICE",
    message: "Input tax claim requires valid tax invoice or import permit.",
    resolved: false,
    status: "Open",
    invoice_no: null,
    created_at: "2026-05-24T09:14:00.000Z"
  },
  {
    id: 3,
    transaction_id: 7,
    severity: "MEDIUM",
    exception_type: "DUPLICATE_INVOICE_NUMBER",
    message: "Duplicate invoice number detected across active sources.",
    resolved: false,
    status: "Needs Follow Up",
    invoice_no: "DUP-3004",
    created_at: "2026-05-24T09:16:00.000Z"
  },
  {
    id: 4,
    transaction_id: 8,
    severity: "MEDIUM",
    exception_type: "FX_RATE_MISSING",
    message: "Foreign currency conversion missing.",
    resolved: false,
    status: "Open",
    invoice_no: "FX-9002",
    created_at: "2026-05-24T09:18:00.000Z"
  }
];

export const mockSummary: GstF5Summary = {
  filing_period_id: mockPeriod.id,
  status: "REVIEW",
  transaction_count: 128,
  exception_count: 7,
  high_exception_count: 2,
  needs_review_count: 6,
  box_1_standard_rated_supplies: 850000,
  box_2_zero_rated_supplies: 120000,
  box_3_exempt_supplies: 30000,
  box_4_total_supplies: 1000000,
  box_5_taxable_purchases: 420000,
  box_6_output_tax_due: 76500,
  box_7_input_tax_claimed: 31500,
  box_8_net_gst_payable: 45000,
  box_13_revenue: 1000000,
  approval_ready: false,
  box_counts: {
    box_1: 68,
    box_2: 14,
    box_3: 5,
    box_4: 87,
    box_5: 41,
    box_6: 68,
    box_7: 35,
    box_8: 128,
    box_13: 87
  }
};

export const mockAudit: AuditLogItem[] = [
  {
    id: 1,
    filing_period_id: mockPeriod.id,
    actor: "SYSTEM",
    actor_type: "AI",
    action: "AI_CLASSIFIED_TRANSACTIONS",
    details: "AI classified 128 transactions and routed low-confidence records for review.",
    affected_item: "classification_batch",
    new_value: "128 classifications",
    reason: "Initial GST treatment recommendation",
    step: "Step 7: AI GST Classification",
    created_at: "2026-05-24T09:22:00.000Z"
  },
  {
    id: 2,
    filing_period_id: mockPeriod.id,
    transaction_id: 10,
    actor: "USER",
    actor_type: "Human",
    action: "HUMAN_OVERRIDE_RECORDED",
    details: "Motor car expense changed to non-claimable input tax.",
    affected_item: "gst_treatment",
    old_value: "TAXABLE_PURCHASE",
    new_value: "DISALLOWED_INPUT_TAX",
    reason: "Motor car expense is not claimable.",
    step: "Step 9: Human Review and Override",
    created_at: "2026-05-24T09:30:00.000Z"
  },
  {
    id: 3,
    filing_period_id: mockPeriod.id,
    transaction_id: 2,
    actor: "SYSTEM",
    actor_type: "AI",
    action: "HIGH_SEVERITY_ANOMALY_DETECTED",
    details: "Zero-rated sale is missing export evidence.",
    affected_item: "evidence_status",
    new_value: "Missing",
    reason: "Export evidence required for zero-rated sale.",
    step: "Step 8: Reconciliation and Anomaly Detection",
    created_at: "2026-05-24T09:34:00.000Z"
  },
  {
    id: 4,
    filing_period_id: mockPeriod.id,
    actor: "SYSTEM",
    actor_type: "System",
    action: "FILING_PACK_GENERATED",
    details: "Draft filing pack prepared for accountant review.",
    affected_item: "filing_pack",
    new_value: "Draft",
    reason: "Prepared for manual submission via IRAS myTax Portal.",
    step: "Step 12: Filing Pack Generation",
    created_at: "2026-05-24T09:42:00.000Z"
  },
  {
    id: 5,
    filing_period_id: mockPeriod.id,
    actor: "USER",
    actor_type: "Manager",
    action: "MANAGER_APPROVAL_PENDING",
    details: "Manager final approval required after blockers are cleared.",
    affected_item: "approval_status",
    new_value: "Pending",
    reason: "High-severity anomalies remain open.",
    step: "Step 13: Final Approval",
    created_at: "2026-05-24T09:50:00.000Z"
  }
];
